### 导入包

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
%matplotlib inline

from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier,XGBRegressor
from mlxtend.classifier import StackingClassifier
import lightgbm as lgb
from sklearn import datasets, linear_model, metrics
from sklearn.metrics import confusion_matrix,accuracy_score, recall_score, f1_score, precision_score,confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV,cross_val_score,cross_val_predict
import sklearn.model_selection as ms

import warnings
warnings.filterwarnings("ignore")


### 导入数据

In [2]:
data=pd.read_csv('./cancer-data.csv')
data=data.drop(['Unnamed: 0'],axis=1)
X=data.drop(['Group'],axis=1)
y=data['Group']

### 数据归一化

In [3]:
column=X.columns
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X=sc.fit_transform(X)

### 划分训练集测试集

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=None)
print(f'Train shape : {X_train.shape}\nTest shape: {X_test.shape}')

Train shape : (128, 202)
Test shape: (33, 202)


### 模型

In [6]:
def crosspredict(estimator,Xtrain,ytrain,cv):
    print("cross-validate across the entire data set")
    y_pred_cross=cross_val_predict(estimator,Xtrain,ytrain,cv=cv)
    confusion_cross=confusion_matrix(ytrain,y_pred_cross)
    a=accuracy_score(ytrain,y_pred_cross)
    p=precision_score(ytrain, y_pred_cross)
    r=recall_score(ytrain, y_pred_cross)
    f1=f1_score(ytrain, y_pred_cross)
    wf1=f1_score(ytrain, y_pred_cross, average='weighted')
    #auc=roc_auc_score(ytrain,estimator.predict_proba(Xtrain)[:,1])
    print('the confusion_matrix of the model is : \n',confusion_cross)
    print('the accuracy of the model is : ',a)
    print("the precision score of the model is : ", p)
    print("the recall score of the model is :", r)
    print('the f1_score of the model  is :',f1)
    print('the weighted_f1 of the model is :',wf1)
    print('the classification_report is :\n',classification_report(ytrain, y_pred_cross,digits=4))
    #print('the auc is :',auc)
    return a,p,r,f1,wf1

In [7]:
#只在测试集上测试
def testpredict(estimator,Xtrain,ytrain,Xtest,ytest):
    print("只在测试集上测试")
    model=estimator.fit(Xtrain,ytrain)
    y_pred_train=model.predict(Xtrain)
    y_pred_test=model.predict(Xtest)
    confusion=confusion_matrix(ytest,y_pred_test)
    acc=accuracy_score(ytest, y_pred_test)
    rec=recall_score(ytest, y_pred_test)
    pre=precision_score(ytest, y_pred_test)
    f1=f1_score(ytest, y_pred_test)
    print('the confusion_matrix of the model is : \n',confusion)
    print('the accuracy of the model on testing set is ：',acc)
    print("the precision score of the model on testing set is : ",pre )
    print("the recall score of the model on testing set is :", rec)
    print('the f1_score of the model on testing set is :',f1)
    
    return acc,pre,rec,f1

#### RandomForestClassifier(),KNeighborsClassifier(),SVC(),AdaBoostClassifier(),
   #### LogisticRegression(),GradientBoostingClassifier(),XGBClassifier(),DecisionTreeClassifier()

In [8]:
model=[RandomForestClassifier(),KNeighborsClassifier(),SVC(),AdaBoostClassifier(),
       LogisticRegression(),GradientBoostingClassifier(),XGBClassifier(),DecisionTreeClassifier()]

In [9]:
for i in range(len(model)):
    print("the model is :",model[i])
    f1_test_before=testpredict(model[i],X_train,y_train,X_test,y_test)
    print("the model is :",model[i])
    f1_cross_before=crosspredict(model[i],X,y,10)
    print("\n")

the model is : RandomForestClassifier()
只在测试集上测试
the confusion_matrix of the model is : 
 [[12  3]
 [ 7 11]]
the accuracy of the model on testing set is ： 0.696969696969697
the precision score of the model on testing set is :  0.7857142857142857
the recall score of the model on testing set is : 0.6111111111111112
the f1_score of the model on testing set is : 0.6875000000000001
the model is : RandomForestClassifier()
cross-validate across the entire data set
the confusion_matrix of the model is : 
 [[52 23]
 [32 54]]
the accuracy of the model is :  0.6583850931677019
the precision score of the model is :  0.7012987012987013
the recall score of the model is : 0.627906976744186
the f1_score of the model  is : 0.6625766871165645
the weighted_f1 of the model is : 0.6586223532025433
the classification_report is :
               precision    recall  f1-score   support

           0     0.6190    0.6933    0.6541        75
           1     0.7013    0.6279    0.6626        86

    accuracy    

the confusion_matrix of the model is : 
 [[47 28]
 [28 58]]
the accuracy of the model is :  0.6521739130434783
the precision score of the model is :  0.6744186046511628
the recall score of the model is : 0.6744186046511628
the f1_score of the model  is : 0.6744186046511628
the weighted_f1 of the model is : 0.6521739130434783
the classification_report is :
               precision    recall  f1-score   support

           0     0.6267    0.6267    0.6267        75
           1     0.6744    0.6744    0.6744        86

    accuracy                         0.6522       161
   macro avg     0.6505    0.6505    0.6505       161
weighted avg     0.6522    0.6522    0.6522       161



the model is : DecisionTreeClassifier()
只在测试集上测试
the confusion_matrix of the model is : 
 [[10  5]
 [ 7 11]]
the accuracy of the model on testing set is ： 0.6363636363636364
the precision score of the model on testing set is :  0.6875
the recall score of the model on testing set is : 0.6111111111111112
the f1_s

### 网格搜索

In [10]:
#Grid Search
def gridsearch(params,estimator,Xtrain,ytrain,cvnumber):
    model = ms.GridSearchCV(estimator, params, cv=cvnumber)
    model.fit(Xtrain, ytrain)
    print("the best_params of the model is:",model.best_params_)
    print("the best_score of the model is:",model.best_score_)
    print("the best_estimator of the model is:",model.best_estimator_)

In [12]:
## svm
params = [
    {'kernel':['linear'], 'C':[1, 10, 100, 1000]},
    {'kernel':['poly'], 'C':[1,10,100], 'degree':[2, 3,4,5],'coef0':[0,1,10,100]}, 
    {'kernel':['rbf'], 'C':[1,10,100], 'gamma':[1, 0.1, 0.01]}]
gridsearch(params,SVC(probability=True),X_train,y_train,10)

the best_params of the model is: {'C': 10, 'coef0': 1, 'degree': 3, 'kernel': 'poly'}
the best_score of the model is: 0.666025641025641
the best_estimator of the model is: SVC(C=10, coef0=1, kernel='poly', probability=True)


In [13]:
#RF
params={
    'n_estimators':np.arange(1,21,1),
    'max_depth': np.arange(1,21,1),
}
model = ms.GridSearchCV(RandomForestClassifier(), params, cv=10)
model.fit(X_train, y_train)

print("the best_params of the RF model is:",model.best_params_)
# 获取最优得分
print("the best_score of the RF model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the RF model is:",model.best_estimator_)

the best_params of the RF model is: {'max_depth': 4, 'n_estimators': 7}
the best_score of the RF model is: 0.7108974358974358
the best_estimator of the RF model is: RandomForestClassifier(max_depth=4, n_estimators=7)


In [14]:
#RF
params={
    'n_estimators':np.arange(1,201,1),
#     'max_depth': np.arange(1,20,1),
}
model = ms.GridSearchCV(RandomForestClassifier(n_jobs=-1,random_state=90), params, cv=10)
model.fit(X_train, y_train)

print("the best_params of the RF model is:",model.best_params_)
# 获取最优得分
print("the best_score of the RF model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the RF model is:",model.best_estimator_)

the best_params of the RF model is: {'n_estimators': 20}
the best_score of the RF model is: 0.7025641025641026
the best_estimator of the RF model is: RandomForestClassifier(n_estimators=20, n_jobs=-1, random_state=90)


In [15]:
#RF
params={
#     'n_estimators':np.arange(1,201,1),
     'max_depth': np.arange(1,20,1),
}
model = ms.GridSearchCV(RandomForestClassifier(n_estimators=105, n_jobs=-1,random_state=90), params, cv=10)
model.fit(X_train, y_train)

print("the best_params of the RF model is:",model.best_params_)
# 获取最优得分
print("the best_score of the RF model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the RF model is:",model.best_estimator_)

the best_params of the RF model is: {'max_depth': 2}
the best_score of the RF model is: 0.6557692307692308
the best_estimator of the RF model is: RandomForestClassifier(max_depth=2, n_estimators=105, n_jobs=-1,
                       random_state=90)


In [16]:
#KNN
params={
    'n_neighbors':np.arange(2,101,1)
} 
gridsearch(params,KNeighborsClassifier(),X_train, y_train,10)

the best_params of the model is: {'n_neighbors': 11}
the best_score of the model is: 0.6576923076923077
the best_estimator of the model is: KNeighborsClassifier(n_neighbors=11)


In [17]:
#AdaBoost
params={
    'n_estimators':[10,50,100,200,300,400,500],
    'learning_rate':[0.0001,0.001,0.01,0.1,1]
}
model = ms.GridSearchCV(AdaBoostClassifier(), params, cv=10)
model.fit(X_train, y_train)

print("the best_params of the AdaBoost model is:",model.best_params_)
# 获取最优得分
print("the best_score of the AdaBoost model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the AdaBoost model is:",model.best_estimator_)

the best_params of the AdaBoost model is: {'learning_rate': 0.1, 'n_estimators': 100}
the best_score of the AdaBoost model is: 0.726923076923077
the best_estimator of the AdaBoost model is: AdaBoostClassifier(learning_rate=0.1, n_estimators=100)


In [18]:
#LR
params={
    'C':[0.0001,0.001,0.01,0.1],
    'max_iter':[100,200,300,400,500]
}
model = ms.GridSearchCV(LogisticRegression(), params, cv=10)
model.fit(X_train, y_train)
print("the best_params of the LogisticRegression model is:",model.best_params_)
# 获取最优得分
print("the best_score of the LogisticRegression model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the LogisticRegression model is:",model.best_estimator_)

the best_params of the LogisticRegression model is: {'C': 0.001, 'max_iter': 100}
the best_score of the LogisticRegression model is: 0.6403846153846154
the best_estimator of the LogisticRegression model is: LogisticRegression(C=0.001)


In [19]:
#Gradient Boosting
params={
    'loss':['deviance','exponential'],
    'n_estimators':[10,50,100,200,300,400,500],
    'learning_rate':[0.0001,0.001,0.01,0.1,1]
}
model = ms.GridSearchCV(GradientBoostingClassifier(), params, cv=10)
model.fit(X_train, y_train)
print("the best_params of the GradientBoost model is:",model.best_params_)
# 获取最优得分
print("the best_score of the GradientBoost model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the GradientBoost model is:",model.best_estimator_)

the best_params of the GradientBoost model is: {'learning_rate': 1, 'loss': 'deviance', 'n_estimators': 50}
the best_score of the GradientBoost model is: 0.6711538461538462
the best_estimator of the GradientBoost model is: GradientBoostingClassifier(learning_rate=1, n_estimators=50)


In [20]:
#XGBoost
params={
    'booster':['gbtree','gblinear'],
    'n_estimators':[10,50,100,200,300,400,500,1000,2000],
    'learning_rate':[0.0001,0.001,0.01,0.05,0.1,0.3,1],
    'max_depth': [5, 10, 15, 20, 25]
}
model = ms.GridSearchCV(XGBClassifier(), params, cv=10)
model.fit(X_train, y_train)
print("the best_params of the XGBoost model is:",model.best_params_)
# 获取最优得分
print("the best_score of the XGBoost model is:",model.best_score_)
# 获取最优模型的信息
print("the best_estimator of the XGBoost model is:",model.best_estimator_)

the best_params of the XGBoost model is: {'booster': 'gblinear', 'learning_rate': 0.0001, 'max_depth': 5, 'n_estimators': 300}
the best_score of the XGBoost model is: 0.6416666666666667
the best_estimator of the XGBoost model is: XGBClassifier(base_score=None, booster='gblinear', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.0001, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)


In [21]:
#decisiontree
from sklearn.tree import DecisionTreeClassifier
params={
    'max_depth':list((5,10,12)),
    'min_samples_split': list((2,4,6)),
    'min_samples_leaf':list((1,2,4))
}
gridsearch(params,DecisionTreeClassifier(),X_train,y_train,10)

the best_params of the model is: {'max_depth': 12, 'min_samples_leaf': 4, 'min_samples_split': 6}
the best_score of the model is: 0.633974358974359
the best_estimator of the model is: DecisionTreeClassifier(max_depth=12, min_samples_leaf=4, min_samples_split=6)


### model comparasion after grid search

In [22]:
modelgrid=[SVC(C=10, coef0=1, degree=3, kernel='poly', probability=True),
       RandomForestClassifier(max_depth=2, n_estimators=105, n_jobs=-1,random_state=90),
       KNeighborsClassifier(n_neighbors=11),
       AdaBoostClassifier(learning_rate=0.1),
       LogisticRegression(C=0.001),
       GradientBoostingClassifier(loss='deviance', n_estimators=50),
       XGBClassifier(booster='gblinear',learning_rate=0.0001,max_depth=5,n_estimators=300),
       DecisionTreeClassifier(max_depth=12, min_samples_leaf=4, min_samples_split=6)]

In [23]:
for i in range(len(modelgrid)):
    print("the model is :",modelgrid[i])
    f1_test_before=testpredict(modelgrid[i],X_train,y_train,X_test,y_test)
    print("the model is :",modelgrid[i])
    f1_cross_before=crosspredict(modelgrid[i],X,y,10)
    print("\n")

the model is : SVC(C=10, coef0=1, kernel='poly', probability=True)
只在测试集上测试
the confusion_matrix of the model is : 
 [[13  2]
 [ 3 15]]
the accuracy of the model on testing set is ： 0.8484848484848485
the precision score of the model on testing set is :  0.8823529411764706
the recall score of the model on testing set is : 0.8333333333333334
the f1_score of the model on testing set is : 0.8571428571428571
the model is : SVC(C=10, coef0=1, kernel='poly', probability=True)
cross-validate across the entire data set
the confusion_matrix of the model is : 
 [[52 23]
 [32 54]]
the accuracy of the model is :  0.6583850931677019
the precision score of the model is :  0.7012987012987013
the recall score of the model is : 0.627906976744186
the f1_score of the model  is : 0.6625766871165645
the weighted_f1 of the model is : 0.6586223532025433
the classification_report is :
               precision    recall  f1-score   support

           0     0.6190    0.6933    0.6541        75
           1    

the confusion_matrix of the model is : 
 [[47 28]
 [32 54]]
the accuracy of the model is :  0.6273291925465838
the precision score of the model is :  0.6585365853658537
the recall score of the model is : 0.627906976744186
the f1_score of the model  is : 0.6428571428571429
the weighted_f1 of the model is : 0.6277325159312738
the classification_report is :
               precision    recall  f1-score   support

           0     0.5949    0.6267    0.6104        75
           1     0.6585    0.6279    0.6429        86

    accuracy                         0.6273       161
   macro avg     0.6267    0.6273    0.6266       161
weighted avg     0.6289    0.6273    0.6277       161



the model is : DecisionTreeClassifier(max_depth=12, min_samples_leaf=4, min_samples_split=6)
只在测试集上测试
the confusion_matrix of the model is : 
 [[12  3]
 [ 9  9]]
the accuracy of the model on testing set is ： 0.6363636363636364
the precision score of the model on testing set is :  0.75
the recall score of the mod